# Generated by Django 3.2 on 2021-11-11 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Credit_card',
            fields=[
                ('id_card', models.PositiveBigIntegerField(default=0, primary_key=True, serialize=False)),
                ('bank', models.CharField(max_length=15)),
                ('expired_day', models.DateTimeField()),
                ('account_name', models.CharField(max_length=100)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rectAPI.account')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id_order', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_order')),
                ('address', models.CharField(max_length=30)),
                ('payment_method', models.BooleanField()),
                ('accumulative_points', models.IntegerField(default=0, null=True)),
                ('date', models.DateField()),
                ('ID_creditcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rectAPI.credit_card')),
                ('ID_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rectAPI.account')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_product')),
                ('url', models.FilePathField()),
                ('price', models.FloatField()),
                ('Point', models.IntegerField()),
                ('is_drink', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='sub_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rectAPI.order')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rectAPI.product')),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_food', models.ForeignKey(limit_choices_to={'is_drink': False}, on_delete=django.db.models.deletion.CASCADE, to='rectAPI.product')),
            ],
        ),
        migrations.CreateModel(
            name='drink',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Medium'), ('XL', 'Big')], max_length=2)),
                ('topping', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('id_drink', models.ForeignKey(limit_choices_to={'is_drink': True}, on_delete=django.db.models.deletion.CASCADE, to='rectAPI.product')),
            ],
        ),
        migrations.CreateModel(
            name='custormer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('dateofbirth', models.DateField()),
                ('Address', models.CharField(max_length=50)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rectAPI.account')),
            ],
        ),
    ]
