# Generated by Django 3.2 on 2021-11-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_card',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='custormer',
            name='id_account',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='id_drink',
        ),
        migrations.RemoveField(
            model_name='food',
            name='id_food',
        ),
        migrations.RemoveField(
            model_name='sub_order',
            name='id_order',
        ),
        migrations.RemoveField(
            model_name='sub_order',
            name='id_product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ID_creditcard',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ID_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='accumulative_points',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='nameofc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='totalcost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='account',
        ),
        migrations.DeleteModel(
            name='Credit_card',
        ),
        migrations.DeleteModel(
            name='custormer',
        ),
        migrations.DeleteModel(
            name='drink',
        ),
        migrations.DeleteModel(
            name='food',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='sub_order',
        ),
    ]
