# Generated by Django 3.2 on 2021-11-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectAPI', '0002_auto_20211117_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='nameofc',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
