# Generated by Django 3.2 on 2021-11-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectAPI', '0003_auto_20211117_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
