# Generated by Django 3.2 on 2021-11-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectAPI', '0004_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='drink',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('protein', models.PositiveIntegerField()),
                ('addictives', models.PositiveIntegerField()),
                ('deco', models.PositiveIntegerField()),
                ('baking', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='hamburger',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('protein', models.PositiveIntegerField()),
                ('addictives', models.PositiveIntegerField()),
                ('deco', models.PositiveIntegerField()),
                ('baking', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('protein', models.PositiveIntegerField(blank=True, null=True)),
                ('addictives', models.PositiveIntegerField(blank=True, null=True)),
                ('deco', models.PositiveIntegerField(blank=True, null=True)),
                ('baking', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
