# Generated by Django 3.2 on 2021-11-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rectAPI', '0006_rename_protein_drink_energy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='baking',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='deco',
        ),
    ]
